hdfs dfs -rm final_project/weather/2007/*
hdfs dfs -rmdir final_project/weather/2007
hdfs dfs -rm final_project/weather/2008/*
hdfs dfs -rmdir final_project/weather/2008
hdfs dfs -rm final_project/weather/2009/*
hdfs dfs -rmdir final_project/weather/2009
hdfs dfs -rm final_project/weather/2010/*
hdfs dfs -rmdir final_project/weather/2010
hdfs dfs -rm final_project/weather/2011/*
hdfs dfs -rmdir final_project/weather/2011
hdfs dfs -rm final_project/weather/2012/*
hdfs dfs -rmdir final_project/weather/2012
hdfs dfs -rm final_project/weather/2013/*
hdfs dfs -rmdir final_project/weather/2013
hdfs dfs -rm final_project/weather/2014/*
hdfs dfs -rmdir final_project/weather/2014
hdfs dfs -rm final_project/weather/2015/*
hdfs dfs -rmdir final_project/weather/2015
hdfs dfs -rm final_project/weather/2016/*
hdfs dfs -rmdir final_project/weather/2016
hdfs dfs -rm final_project/weather/2017/*
hdfs dfs -rmdir final_project/weather/2017

